version: '3'
services:
  web:
    image: ther12k/joingateocrmonitoring
    container_name: joingateocrmonitoring-dev
    environment:
      - API_URL=http://api:8080/api  # Use the service name 'api' as the hostname
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx-logs:/var/log/nginx
    depends_on:
      - api

  api:
    image: ther12k/joingateocrapi
    environment:
      - ASPNETCORE_ENVIRONMENT=development
      - TZ=Asia/Jakarta
    container_name: joingateocrapi-dev
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "./logs:/logs"
